FROM php:8.1-fpm

RUN set -eux \
	&& DEBIAN_FRONTEND=noninteractive apt-get update -qq \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --no-install-recommends --no-install-suggests apt-utils \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --no-install-recommends --no-install-suggests \
		alien \
		libevent-dev \
		libcurl4-openssl-dev \
                firebird-dev \
                libaio-dev \
                libbz2-dev \
                libc-client-dev \
		libfbclient2 \
                libfreetype6-dev \
                libgmp-dev \
                libib-util \
                libicu-dev \
                libjpeg-dev \
                libkrb5-dev \
                libldap2-dev \
                libmcrypt-dev \
                libmemcached-dev \
                libpcre3-dev \
                libpng-dev \
                libpq-dev \
                libpspell-dev \
                libsasl2-dev \
                libsnmp-dev \
                libsodium-dev \
                libssl-dev \
                libtidy-dev \
                libvpx-dev \
                libwebp-dev \
                libxml2-dev \
                libxpm-dev \
                libxslt-dev \
                libyaml-dev \
                libzip-dev \
                snmp \
                zlib1g-dev \
                ca-certificates \
                git \
		        gettext-base \
		        zip \
                iproute2

RUN set -eux \
        && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) sockets \
        && true

RUN set -eux \
        && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) pdo_mysql \
        && true

RUN set -eux \
        && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) zip \
        && true

RUN set -eux \
    && git clone https://github.com/xdebug/xdebug /tmp/xdebug \
    && cd /tmp/xdebug \
    && git checkout $(git for-each-ref --format='%(refname)' refs/tags | grep -E 'tags/[.0-9]+$' | sed 's|.*tags/||g' | sort -V | tail -1) \
    && phpize \
    && ./configure  --enable-xdebug \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \
    && docker-php-ext-enable xdebug \
    && true

ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ADD composer/auth.json /root/.composer/auth.json

RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
ADD php-local.ini /usr/local/etc/php/conf.d/zzz-custom.ini

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint
COPY docker-entrypoint-local.sh /usr/local/bin/docker-entrypoint-local
RUN chmod +x /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint-local
ENTRYPOINT ["/usr/local/bin/docker-entrypoint", "/usr/local/bin/docker-entrypoint-local"]

WORKDIR /var/www/app

CMD ["php-fpm"]