version: '3'
services:
  mysql:
    container_name: my-service-mysql
    image: mysql:5.7
    ports:
      - "${APP_MYSQL_PORT}:${APP_MYSQL_PORT}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_DATABASE: ${APP_MYSQL_DB}
      MYSQL_PASSWORD: ${APP_MYSQL_PASS}
      MYSQL_USER: ${APP_MYSQL_USER}
    network_mode: bridge
    restart: always
  nginx:
    build: ./docker/nginx
    container_name: my-service-nginx
    env_file: .env
    links:
      - php
    network_mode: bridge
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    restart: always
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./:/var/www/app
  php:
    build:
      context: ./docker/php
    env_file: .env
    container_name: my-service-php
    links:
      - mysql
    network_mode: bridge
    restart: always
    volumes:
      - ./:/var/www/app