version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: my-service-nginx
    env_file: .env
    links:
      - php
    network_mode: bridge
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./:/var/www/app
    restart: always
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile-local
    env_file: .env
    container_name: my-service-php
    external_links:
      - local-mysql
    network_mode: bridge
    volumes:
      - ./:/var/www/app
    restart: always